backend:
  name: git-gateway      # 使用 Netlify Identity + Git Gateway
  branch: main           # 你网站的主分支

media_folder: "images"    # 上传图片保存到 images/
public_folder: "/images"  # 前台访问路径

collections:
  - name: "products"
    label: "商品管理"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    format: json
    fields:
      - { label: "名称", name: "name", widget: "string" }
      - { label: "描述", name: "desc", widget: "text" }
      - { label: "价格", name: "price", widget: "number", value_type: "float" }
      - { label: "标签", name: "tags", widget: "list" }
      - { label: "图片", name: "imgs", widget: "list" }
